stages:
  - test
  - publish
  - deploy

unit tests:
  image: python:3
  before_script:
    - pip install -r api/api_gateway/requirements/dev.txt
  stage: test
  script:
    - cd api && sh run-tests.sh

publish codecov:
  image: python:3
  before_script:
    - pip install -r api/api_gateway/requirements/dev.txt
  only:
    - master
  stage: publish
  dependencies:
    - unit tests
  script:
    - cd api && sh run-tests.sh
    - cd api_gateway && codecov -t ${CODECOV_TOKEN}

# github pages
publish pages:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  only:
    - master
  stage: publish
  script:
    - sh run-publish-pages.sh

publish image to production:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  before_script:
    - docker info
  only:
    - tags
  stage: publish
  script:
    - cd api && sh run-publish-docker.sh production

# publish image to staging:
#   image: docker:stable
#   services:
#     - docker:dind
#     - docker:python:3
#   before_script:
#     - docker info
#   only:
#     - dev
#   stage: publish
#   script:
#     - cd api && sh run-publish-docker.sh staging

deploy to production:
  image: python:3
  only:
    - tags
  stage: deploy
  script:
    - cd api
    - sh install-kubectl.sh
    - sh run-deploy.sh production

# deploy to staging:
#   image: python:3
#   only:
#     - dev
#   stage: deploy
#   script:
#     - cd api
#     - sh install-kubectl.sh
#     - sh run-deploy.sh staging

deploy to heroku:
  stage: deploy
  script:
  - gem install dpl
  - cd api_gateway && dpl --provider=heroku --app=integra-vendas-api-gateway --api-key=$HEROKU_DEV_KEY
  only:
  - dev