stages:
  - test
  - publish
  - deploy

# github pages
publish pages:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  only:
    - master
  stage: publish
  script:
    - sh run-publish-pages.sh

publish image to production:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  before_script:
    - docker info
  only:
    - tags
  stage: publish
  script:
    - cd api && sh run-publish-docker.sh production

publish image to staging:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  before_script:
    - docker info
  only:
    - dev
  stage: publish
  script:
    - cd api && sh run-publish-docker.sh staging

deploy to production:
  image: python:3.5.6-slim-stretch
  only:
    - tags
  stage: deploy
  script:
    - cd api
    - sh install-kubectl.sh
    - sh run-deploy.sh production

# deploy to staging:
#   image: python:3
#   only:
#     - dev
#   stage: deploy
#   script:
#     - cd api
#     - sh install-kubectl.sh
#     - sh run-deploy.sh staging

deploy to heroku:
  stage: deploy
  script:
  - gem install dpl
  - cd api/api_gateway && dpl --provider=heroku --app=integra-vendas-api-gateway --api-key=$HEROKU_DEV_KEY
  only:
  - dev