stages:
  - test
  - publish
  - deploy

# github pages
publish pages:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  only:
    - master
  stage: publish
  script:
    - sh run-publish-pages.sh

publish image to production:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  before_script:
    - docker info
  only:
    - tags
  stage: publish
  script:
    - cd api && sh run-publish-docker.sh production

publish image to staging:
  image: docker:stable
  services:
    - docker:dind
    - docker:python:3
  before_script:
    - docker info
  only:
    - dev
  stage: publish
  script:
    - cd api && sh run-publish-docker.sh staging

deploy to production:
  image: python:3.5.6-slim-stretch
  only:
    - tags
  stage: deploy
  script:
    - cd api
    - sh install-kubectl.sh
    - sh run-deploy.sh production

# deploy to heroku:
#   stage: deploy
#   script:
#     - . ./heroku-helper.sh
#     - updateVersion api/VERSION
#     - loginHeroku $EMAIL_HEROKU $HEROKU_DEV_KEY
#     - deployMaster $HEROKU_APP api/api_gateway
#   only:
#     - dev