# .travis.yml
language: python
python:
  - "3.4"

cache: pip

install:
  - pip install -r api/api_gateway/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages:
  - test

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: cd api && sh run-tests.sh