cache: pip
git: 
  depth: false
install: 
  - "pip install -r api/api_gateway/requirements/dev.txt"
jobs: 
  include: 
    - 
      branches: 
        only: 
          - master
      name: "Checking Production Container Run"
      script: 
        - "cd api && make check-docker-production"
      services: 
        - docker
      stage: check
      sudo: required
    - 
      name: "Checking Development Container Run"
      script: 
        - "cd api && make check-docker-dev"
      services: 
        - docker
      stage: check
      sudo: required
    - 
      name: "Staging Integration"
      script: 
        - "make integration-tests file=dc-integration-test.staging.yml"
      services: 
        - docker
      stage: test
    - 
      branches: 
        only: 
          - dev
      name: "Staging Integration codecov publish"
      script: 
        - "make integration-tests file=dc-integration-test.staging.yml"
        - "cd api/api_gateway && codecov -t ${CODECOV_TOKEN}"
      services: 
        - docker
      stage: test
    - 
      branches: 
        only: 
          - master
      name: "Production Integration"
      script: 
        - "make integration-tests file=dc-integration-test.production.yml"
      stage: test
    - 
      if: "branch = master"
      name: "Publish production images on docker hub"
      script: 
        - "cd api && sh run-publish-docker.sh production"
      services: 
        - docker
      stage: build
      sudo: required
    - 
      if: "branch = dev"
      name: "Publish staging images on docker hub"
      script: 
        - "cd api && sh run-publish-docker.sh staging"
      services: 
        - docker
      stage: build
      sudo: required
    - 
      if: "branch = dev"
      install: "npm install -g heroku"
      name: "Deploying to Staging"
      script: 
        - ". ./heroku-helper.sh"
        - "updateVersion api/VERSION"
        - "loginHeroku $EMAIL_HEROKU $HEROKU_DEV_KEY"
        - "deployMaster $HEROKU_APP api/api_gateway"
      stage: deploy
    - 
      if: "branch = /(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
      name: "Deploying to Production"
      script: 
        - "cd api"
        - "sh install-kubectl.sh"
        - "sh run-deploy.sh production"
      stage: deploy
    - 
      if: "branch = master"
      name: "Publishing GH-Pages"
      script: 
        - "sh run-publish-pages.sh"
      services: 
        - docker
      stage: deploy
      sudo: required

language: python
python: 
  - "3.4"
services: 
  - docker
stages:
  - test
  - check
  - build
  - deploy
sudo: required
virtualenv: 
  system_site_packages: true