# .travis.yml
sudo: required

language: python
python:
  - "3.4"

cache: pip

install:
  - pip install -r api/api_gateway/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages:
  - Staging Tests
  - Production Tests

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: "Staging Tests"
      name: "Unit Integrated Tests"
      if: branch = dev
      script: make staging-integration-tests

    - stage: "Publish codecov"
      name: "Publishing test coverage"
      # if: branch = dev
      script: sh publish-codecov.sh dc-integration-test.staging.yml

    - stage: "Production Tests"
      name: "Unit Integrated Tests"
      if: branch = master
      script: make production-integration-tests