sudo: required

language: python
python:
  - "3.4"

cache: pip

install:
  - pip install -r api/api_gateway/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages: 
  - integration-tests
  - check-container

services:
  - docker

jobs:
  include:
    - stage: check-container
      sudo: required
      services:
        - docker
      name: "Checking Production Container Run"
      script:
        - cd api && make check-docker-production

    - stage: check-container
      sudo: required
      services:
        - docker
      name: "Checking Development Container Run"
      script:
        - cd api && make check-docker-dev

    - stage: integration-tests
      name: "Staging Integration"
      script:
        - make integration-tests file=dc-integration-test.staging.yml
        - cd api/api_gateway && codecov -t ${CODECOV_TOKEN}

    - stage: integration-tests
      name: "Production Integration"
      if: branch = master
      script:
        - make integration-tests file=dc-integration-test.production.yml
        - cd api/api_gateway && codecov -t ${CODECOV_TOKEN}