sudo: required

language: python
python:
  - "3.4"

cache: pip

install:
  - pip install -r api/api_gateway/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages: 
  - test
  - deploy

services:
  - docker

jobs:
  include:
    - stage: test
      sudo: required
      services:
        - docker
      name: "Checking Production Container Run"
      script:
        - cd api && make check-docker-production

    - stage: test
      sudo: required
      services:
        - docker
      name: "Checking Development Container Run"
      script:
        - cd api && make check-docker-dev

    - stage: test
      name: "Staging Integration"
      script:
        - make integration-tests file=dc-integration-test.staging.yml
        - cd api/api_gateway && codecov -t ${CODECOV_TOKEN}

    - stage: test
      name: "Production Integration"
      if: branch = master
      script:
        - make integration-tests file=dc-integration-test.production.yml
        - cd api/api_gateway && codecov -t ${CODECOV_TOKEN}

    - stage: deploy
      install: npm install -g heroku
      name: "Deploying to Staging"
      only:
        - dev
      script:
        - . ./heroku-helper.sh
        - updateVersion api/VERSION
        - loginHeroku $EMAIL_HEROKU $HEROKU_DEV_KEY
        - deployMaster $HEROKU_APP api/api_gateway