sudo: required

language: python
python:
  - "3.4"

cache: pip

git:
  depth: false

install:
  - pip install -r api/api_gateway/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages:
  - test
  - check
  - build
  - deploy

services:
  - docker

jobs:
  include:
    - stage: check
      name: "Checking Production Container Run"
      sudo: required
      services:
        - docker
      if: branch = master
      script:
        - cd api && make check-docker-production

    - stage: check
      name: "Checking Development Container Run"
      sudo: required
      services:
        - docker
      script:
        - cd api && make check-docker-dev

    - stage: test
      name: "Staging Integration"
      script:
        - make integration-tests file=dc-integration-test.staging.yml
        - cd api/api_gateway && codecov -t ${CODECOV_TOKEN}

    - stage: test
      name: "Production Integration"
      branches:
        only:
          - master
      script:
        - make integration-tests file=dc-integration-test.production.yml
        - cd api/api_gateway && codecov -t ${CODECOV_TOKEN}

    - stage: build
      name: "Publish production images on docker hub"
      sudo: required
      services:
        - docker
      script:
        - cd api && sh run-publish-docker.sh production

    - stage: build
      name: "Publish staging images on docker hub"
      sudo: required
      services:
        - docker
      script:
        - cd api && sh run-publish-docker.sh staging

    - stage: deploy
      name: "Deploying to Staging"
      install: npm install -g heroku
      if: branch = dev
      script:
        - . ./heroku-helper.sh
        - updateVersion api/VERSION
        - loginHeroku $EMAIL_HEROKU $HEROKU_DEV_KEY
        - deployMaster $HEROKU_APP api/api_gateway

    - stage: deploy
      name: "Deploying to Production"
      on:
        tags: true
        branch:
          - master
          - /(\d+\.)?(\d+\.)?(\*|\d+)$/
      script:
        - cd api
        - sh install-kubectl.sh
        - sh run-deploy.sh production

    - stage: deploy
      name: "Publishing GH-Pages"
      sudo: required
      services:
        - docker
      if: branch = master
      script:
        - sh run-publish-pages.sh