version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: api
    container_name: api-gateway
    command: bash -c "bash"
    volumes:
      - ./api:/code
    ports:
      - 5000:8000
    depends_on:
      - db
      - login
      - order
      - product
    stdin_open: true
    tty: true

  login:
    container_name: login-microservice
    image: integravendas/login-microservice:latest-stable
    depends_on:
      - db
    ports:
      - 8000:8000

  order:
    container_name: order-microservice
    image: integravendas/order-microservice:latest-stable
    depends_on:
      - db
    ports:
      - 8001:8000

  product:
    container_name: product-microservice
    image: integravendas/product-microservice:latest-stable
    depends_on:
      - db
    ports:
      - 8002:8000

volumes:
  postgres_data: