version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    command: bash -c "sleep 3; while !</dev/tcp/db/5432; do sleep 1; done;gunicorn --bind 0.0.0.0:8000 api_gateway.wsgi --log-file -"
    ports:
      - 5000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=api_gateway.settings.production-test

volumes:
  postgres_data: