version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  web:
    container_name: "api-gateway"
    build:
      context: .
      dockerfile: production.Dockerfile
    entrypoint: bash -c "bash check-db-service.sh && gunicorn --bind 0.0.0.0:8000 api_gateway.wsgi --log-file -"
    ports:
      - 5000:8000
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=api_gateway.settings.production

volumes:
  postgres_data: