version: '3.3'

services:
  web:
    container_name: "api-gateway"
    build:
      context: .
      dockerfile: production.Dockerfile
    command: bash -c "gunicorn --bind 0.0.0.0:8000 api_gateway.wsgi --log-file -"
    ports:
      - 5000:8000
    volumes:
      - .:/code